from . import connector_mapping
from . import connector_queue
from . import connector_mixin
from . import connector_receivers
from . import connector_settings
from . import res_partner
from . import product_template
from . import uom_uom
from . import product_pricelist
from . import sale_order
