# -*- coding: utf-8 -*-
import logging
from odoo import models, fields, api, _
from odoo.exceptions import UserError
from odoo.api import Environment
from odoo.modules.registry import Registry as odoo_registry

_logger = logging.getLogger(__name__)


class SaleOrder(models.Model):
    _inherit = 'sale.order'

    intercompany_flow_log_ids = fields.One2many(
        'intercompany.flow.log', 'origin_sale_id',
        string='Intercompany Flow Logs',
    )
    intercompany_flow_count = fields.Integer(
        compute='_compute_intercompany_flow_count',
        string='Intercompany Flows',
    )
    is_intercompany_so = fields.Boolean(
        string='Intercompany Auto Flow SO',
        default=False,
        copy=False,
        help='Set to True on SOs that were auto-generated by the intercompany '
             'flow engine. Prevents the trigger from re-firing on these orders '
             'and causing circular sourcing chains.',
    )

    @api.depends('intercompany_flow_log_ids')
    def _compute_intercompany_flow_count(self):
        for order in self:
            order.intercompany_flow_count = len(order.intercompany_flow_log_ids)

    intercompany_invoice_count = fields.Integer(
        compute='_compute_intercompany_invoice_count',
        string='Intercompany Invoices',
    )

    @api.depends('intercompany_flow_log_ids.customer_invoice_id')
    def _compute_intercompany_invoice_count(self):
        for order in self:
            order.intercompany_invoice_count = len(
                order.intercompany_flow_log_ids.mapped('customer_invoice_id').filtered(bool)
            )

    def action_view_intercompany_invoices(self):
        """Open customer invoices generated by the intercompany flow."""
        self.ensure_one()
        invoice_ids = self.intercompany_flow_log_ids.mapped('customer_invoice_id').filtered(bool).ids
        return {
            'name': _('Intercompany Invoices'),
            'type': 'ir.actions.act_window',
            'res_model': 'account.move',
            'view_mode': 'list,form',
            'domain': [('id', 'in', invoice_ids)],
        }

    def action_confirm(self):
        res = super().action_confirm()
        for order in self:
            _logger.warning(
                'ICF CHECK: SO %s | company=%s | auto_flow=%s | is_ic_so=%s',
                order.name,
                order.company_id.name,
                order.company_id.intercompany_auto_flow,
                order.is_intercompany_so,
            )
            if order.company_id.intercompany_auto_flow and not order.is_intercompany_so:
                order._trigger_intercompany_flow()
        return res

    # ─────────────────────────────────────────────────────────────────────────
    # Core orchestration
    # ─────────────────────────────────────────────────────────────────────────

    def _trigger_intercompany_flow(self):
        """For each SO line with a storable product, check local stock and
        automatically source any shortage from one or more sibling companies.

        Algorithm:
          1. Compute shortage = ordered qty - local unreserved stock.
          2. Build a ranked list of ALL sibling companies with available stock
             (ranked: highest qty first, minimises number of POs raised).
          3. If one company can cover the full shortage -> single PO/SO pair.
          4. If no single company can -> split across multiple companies,
             each getting a separate PO/SO pair for its portion.
          5. If total available across all siblings < shortage -> create POs
             for what's available, warn on chatter about unfulfilled remainder.
        """
        self.ensure_one()
        selling_company = self.company_id
        _logger.warning('ICF: _trigger_intercompany_flow called for SO %s (%s lines)', self.name, len(self.order_line))

        for line in self.order_line.filtered(
            lambda l: l.product_id and l.product_id.type != 'service'
                      and (
                          getattr(l.product_id, 'is_storable', False)
                          or l.product_id.type == 'product'
                      )
        ):
            _logger.warning(
                'ICF: Processing line — product=%s type=%s is_storable=%s',
                line.product_id.display_name,
                line.product_id.type,
                getattr(line.product_id, 'is_storable', 'N/A'),
            )
            needed_qty = line.product_uom_qty
            local_qty  = self._get_local_available_qty(line.product_id, selling_company)
            shortage   = needed_qty - local_qty

            if shortage <= 0:
                continue  # Enough local stock — nothing to do

            _logger.warning(
                'ICF: %s needs %.2f of %s; local %.2f -> shortage %.2f',
                selling_company.name, needed_qty,
                line.product_id.display_name, local_qty, shortage,
            )

            # ── Rank ALL sibling companies by available qty (desc) ────────
            ranked = self._rank_supplier_companies(line.product_id, selling_company)
            # ranked = [(company, avail_qty), ...] highest stock first

            if not ranked:
                self._warn_no_stock(line, shortage)
                continue

            # ── Single-source: best company alone covers the shortage ──────
            best_company, best_qty = ranked[0]
            if best_qty >= shortage:
                _logger.warning(
                    'ICF: Single-source -> %s has %.2f (need %.2f)',
                    best_company.name, best_qty, shortage,
                )
                self._create_intercompany_pair(
                    line=line,
                    qty=shortage,
                    buying_company=selling_company,
                    supplying_company=best_company,
                )
                continue

            # ── Split-source: spread across multiple companies ────────────
            total_available = sum(qty for _, qty in ranked)
            _logger.warning(
                'ICF: Split-source needed — total available %.2f across %d '
                'companies for shortage %.2f',
                total_available, len(ranked), shortage,
            )

            remaining = shortage
            for supplier_company, avail_qty in ranked:
                if remaining <= 0:
                    break
                portion = min(avail_qty, remaining)
                _logger.warning(
                    'ICF: Sourcing %.2f from %s (avail %.2f)',
                    portion, supplier_company.name, avail_qty,
                )
                self._create_intercompany_pair(
                    line=line,
                    qty=portion,
                    buying_company=selling_company,
                    supplying_company=supplier_company,
                )
                remaining -= portion

            if remaining > 0:
                self._warn_partial_stock(
                    line, shortage,
                    sourced=shortage - remaining,
                    unfulfilled=remaining,
                )

    # ─────────────────────────────────────────────────────────────────────────
    # Stock helpers
    # ─────────────────────────────────────────────────────────────────────────

    def _get_local_available_qty(self, product, company):
        """Return unreserved on-hand qty of *product* across all internal
        locations owned by *company*."""
        internal_locations = self.env['stock.location'].sudo().search([
            ('company_id', '=', company.id),
            ('usage', '=', 'internal'),
        ])
        if not internal_locations:
            return 0.0
        quants = self.env['stock.quant'].sudo().search([
            ('product_id', '=', product.id),
            ('location_id', 'in', internal_locations.ids),
        ])
        return max(
            0.0,
            sum(quants.mapped('quantity')) - sum(quants.mapped('reserved_quantity'))
        )

    def _rank_supplier_companies(self, product, buying_company):
        """Scan ALL candidate sibling companies and return a ranked list of
        (company, available_qty) sorted by available qty descending.

        Ranking highest-first means:
          - We always prefer a single supplier over a split when possible.
          - When splitting is unavoidable, we exhaust the largest source
            first, minimising the total number of PO/SO pairs created.
        """
        candidates = buying_company._get_intercompany_supplier_candidates()
        ranked = []
        for company in candidates:
            avail = self._get_local_available_qty(product, company)
            _logger.warning(
                'ICF: Scanning %s -> %.2f available of %s',
                company.name, avail, product.display_name,
            )
            if avail > 0:
                ranked.append((company, avail))

        ranked.sort(key=lambda x: x[1], reverse=True)
        return ranked

    # ─────────────────────────────────────────────────────────────────────────
    # Chatter warnings
    # ─────────────────────────────────────────────────────────────────────────

    def _warn_no_stock(self, line, shortage):
        self.message_post(
            body=_(
                'Intercompany Auto Flow: No sibling company has any stock of '
                '<b>%(product)s</b> (shortage: %(qty).2f %(uom)s). '
                'Please source manually.',
                product=line.product_id.display_name,
                qty=shortage,
                uom=line.product_uom_id.name,
            )
        )

    def _warn_partial_stock(self, line, shortage, sourced, unfulfilled):
        self.message_post(
            body=_(
                'Intercompany Auto Flow: <b>%(product)s</b> — shortage was '
                '%(shortage).2f %(uom)s. Sourced %(sourced).2f %(uom)s from '
                'sibling companies across multiple POs. '
                '<b>%(unfulfilled).2f %(uom)s still unfulfilled</b> — '
                'please source the remainder manually.',
                product=line.product_id.display_name,
                uom=line.product_uom_id.name,
                shortage=shortage,
                sourced=sourced,
                unfulfilled=unfulfilled,
            )
        )

    # ─────────────────────────────────────────────────────────────────────────
    # Document creation
    # ─────────────────────────────────────────────────────────────────────────

    def _create_intercompany_pair(self, line, qty, buying_company, supplying_company):
        """Create a PO in *buying_company* and a matching SO in
        *supplying_company*, confirm both, and write a flow log entry."""
        log = self.env['intercompany.flow.log'].sudo().create({
            'name': self.env['ir.sequence'].next_by_code('intercompany.flow.log') or 'ICF-NEW',
            'origin_sale_id': self.id,
            'buying_company_id': buying_company.id,
            'supplying_company_id': supplying_company.id,
            'product_id': line.product_id.id,
            'product_qty': qty,
            'product_uom_id': line.product_uom_id.id,
            'state': 'draft',
        })

        try:
            # Step 1: Purchase Order in buying company
            po = self._create_intercompany_po(
                line=line, qty=qty,
                buying_company=buying_company,
                supplying_company=supplying_company,
            )
            log.purchase_order_id = po.id

            # Step 2: Sales Order in supplying company
            ic_so = self._create_intercompany_so(
                line=line, qty=qty,
                buying_company=buying_company,
                supplying_company=supplying_company,
                purchase_order=po,
            )
            log.intercompany_sale_id = ic_so.id

            # Step 3: Auto-confirm
            if supplying_company.intercompany_sale_auto_confirm:
                ic_so.with_company(supplying_company).action_confirm()

            if buying_company.intercompany_purchase_auto_confirm:
                po.with_company(buying_company).button_confirm()

            # Step 4: Record picking counts for traceability
            log.stock_picking_out_count = len(ic_so.picking_ids)
            log.stock_picking_in_count = len(po.picking_ids)

            # Step 5: Auto-validate pickings if configured
            # Schedule as post-commit so pickings are fully committed and
            # stock is reserved before we attempt to validate them.
            # Variables are passed as default args to avoid Python closure
            # capture bug when multiple flows run in the same transaction.
            if buying_company.intercompany_auto_validate_pickings:
                def _make_validate_hook(_out_ids, _in_ids, _sc_id, _bc_id, _dbname, _uid, _self):
                    def _validate_after_commit():
                        try:
                            with odoo_registry(_dbname).cursor() as new_cr:
                                new_env = Environment(new_cr, _uid, {})
                                out_pickings = new_env['stock.picking'].browse(_out_ids)
                                in_pickings = new_env['stock.picking'].browse(_in_ids)
                                sc = new_env['res.company'].browse(_sc_id)
                                bc = new_env['res.company'].browse(_bc_id)
                                _self.with_env(new_env)._auto_validate_pickings(
                                    out_pickings=out_pickings,
                                    in_pickings=in_pickings,
                                    supplying_company=sc,
                                    buying_company=bc,
                                )
                                new_cr.commit()
                        except Exception as e:
                            _logger.warning('ICF: Post-commit picking validation failed: %s', e)
                    return _validate_after_commit

                self.env.cr.postcommit.add(_make_validate_hook(
                    list(ic_so.picking_ids.ids),
                    list(po.picking_ids.ids),
                    supplying_company.id,
                    buying_company.id,
                    self.env.cr.dbname,
                    self.env.uid,
                    self,
                ))

            # Step 6: Auto-create bills and invoices if configured
            # Also scheduled post-commit so documents are fully persisted first.
            if buying_company.intercompany_auto_invoice:
                def _make_invoice_hook(_po_id, _ic_so_id, _bc_id, _sc_id, _log_id, _dbname, _uid, _self):
                    def _invoice_after_commit():
                        try:
                            with odoo_registry(_dbname).cursor() as new_cr:
                                new_env = Environment(new_cr, _uid, {})
                                po_rec = new_env['purchase.order'].browse(_po_id)
                                ic_so_rec = new_env['sale.order'].browse(_ic_so_id)
                                bc = new_env['res.company'].browse(_bc_id)
                                sc = new_env['res.company'].browse(_sc_id)
                                log_rec = new_env['intercompany.flow.log'].browse(_log_id)
                                _self.with_env(new_env)._create_intercompany_invoices(
                                    po=po_rec,
                                    ic_so=ic_so_rec,
                                    buying_company=bc,
                                    supplying_company=sc,
                                    log=log_rec,
                                )
                                new_cr.commit()
                        except Exception as e:
                            _logger.warning('ICF: Post-commit invoice creation failed: %s', e)
                    return _invoice_after_commit

                self.env.cr.postcommit.add(_make_invoice_hook(
                    po.id,
                    ic_so.id,
                    buying_company.id,
                    supplying_company.id,
                    log.id,
                    self.env.cr.dbname,
                    self.env.uid,
                    self,
                ))

            log.state = 'done'

            # Step 5: Chatter
            self.message_post(
                body=_(
                    'Intercompany Auto Flow: '
                    '<a href="/odoo/purchase/%(po_id)s">%(po_name)s</a> '
                    '(PO in %(buyer)s) &#8596; '
                    '<a href="/odoo/sales/%(so_id)s">%(so_name)s</a> '
                    '(SO in %(supplier)s) &mdash; '
                    '<b>%(product)s &times; %(qty).2f %(uom)s</b>.',
                    po_id=po.id, po_name=po.name,
                    buyer=buying_company.name,
                    so_id=ic_so.id, so_name=ic_so.name,
                    supplier=supplying_company.name,
                    product=line.product_id.display_name,
                    qty=qty, uom=line.product_uom_id.name,
                )
            )
            _logger.warning('ICF: Complete — PO %s <-> SO %s', po.name, ic_so.name)

        except Exception as exc:
            log.state = 'error'
            log.error_message = str(exc)
            _logger.exception('ICF: Flow failed — %s', exc)
            self.message_post(
                body=_(
                    'Intercompany Auto Flow ERROR for <b>%(product)s</b> '
                    '(%(buyer)s <- %(supplier)s): %(err)s',
                    product=line.product_id.display_name,
                    buyer=buying_company.name,
                    supplier=supplying_company.name,
                    err=exc,
                )
            )

    def _auto_validate_pickings(self, out_pickings, in_pickings, supplying_company, buying_company):
        """Validate all pickings using button_validate() — confirmed working in bash tests."""

        def _validate(pickings, company):
            for picking in pickings.sudo().with_company(company):
                _logger.warning('ICF VALIDATE: Picking %s state=%s company=%s move_lines=%s',
                                picking.name, picking.state, company.name, len(picking.move_line_ids))
                if picking.state in ('done', 'cancel'):
                    _logger.warning('ICF VALIDATE: Skipping %s already %s', picking.name, picking.state)
                    continue
                try:
                    if picking.state not in ('assigned',):
                        _logger.warning('ICF VALIDATE: Assigning %s', picking.name)
                        picking.action_assign()

                    for ml in picking.move_line_ids:
                        reserved = (
                            getattr(ml, 'quantity_product_uom', None)
                            or getattr(ml, 'reserved_uom_qty', None)
                            or getattr(ml, 'reserved_qty', None)
                            or ml.move_id.product_uom_qty
                        )
                        ml.quantity = reserved

                    for move in picking.move_ids.filtered(
                        lambda m: m.state not in ('done', 'cancel')
                    ):
                        if not move.move_line_ids:
                            move.quantity = move.product_uom_qty

                    _logger.warning('ICF VALIDATE: Calling button_validate on %s', picking.name)
                    result = picking.with_context(
                        skip_sms=True,
                        skip_backorder=True,
                        immediate_transfer=True,
                    ).button_validate()
                    _logger.warning('ICF VALIDATE: Result=%s state_after=%s', result, picking.state)

                    if isinstance(result, dict) and result.get('res_model'):
                        wizard_model = result['res_model']
                        _logger.warning('ICF VALIDATE: Wizard returned: %s', wizard_model)
                        if 'backorder' in wizard_model.lower():
                            wizard = picking.env[wizard_model].with_context(
                                result.get('context', {})
                            ).create({})
                            if hasattr(wizard, 'process'):
                                wizard.process()
                            elif hasattr(wizard, 'action_cancel_backorder'):
                                wizard.action_cancel_backorder()

                    _logger.warning('ICF VALIDATE: Done %s final_state=%s', picking.name, picking.state)

                except Exception as exc:
                    _logger.warning('ICF VALIDATE: Error on %s: %s', picking.name, exc)

        _logger.warning('ICF VALIDATE: Starting out=%s in=%s', out_pickings.ids, in_pickings.ids)
        _validate(out_pickings, supplying_company)
        _validate(in_pickings, buying_company)

    def _create_intercompany_invoices(self, po, ic_so, buying_company, supplying_company, log=None):
        """Create and post:
          - A vendor bill (in_invoice) in the buying company from the PO lines
          - A customer invoice (out_invoice) in the supplying company from the SO lines
        Compatible with both standard Odoo 19 and base_accounting_kit.
        """
        AccountMove = self.env['account.move'].sudo()

        def _get_account(product, company, account_type):
            """Find income or expense account for a product using get_product_accounts."""
            try:
                accs = product.with_company(company).product_tmpl_id.get_product_accounts()
                acc = accs.get(account_type)
                if acc:
                    return acc
            except Exception:
                pass
            # Fallback: search by account_type
            type_map = {
                'income': ('income', 'income_other'),
                'expense': ('expense', 'expense_direct_cost'),
            }
            return self.env['account.account'].sudo().with_company(company).search([
                ('account_type', 'in', type_map[account_type]),
                ('active', '=', True),
            ], limit=1)

        def _get_journal(company, journal_type):
            """Find a purchase or sale journal for the given company.
            journal_type: 'purchase' or 'sale'
            """
            Journal = self.env['account.journal'].sudo().with_company(company)
            journal = Journal.search([
                ('type', '=', journal_type),
                ('company_id', '=', company.id),
            ], limit=1)
            if not journal:
                _logger.warning('ICF: No %s journal found in %s', journal_type, company.name)
            return journal

        # ── Vendor Bill in buying company ─────────────────────────────────
        try:
            purchase_journal = _get_journal(buying_company, 'purchase')
            bill_lines = []
            for pol in po.order_line:
                account = _get_account(pol.product_id, buying_company, 'expense')
                if not account:
                    _logger.warning('ICF: No expense account for %s in %s',
                                    pol.product_id.display_name, buying_company.name)
                    continue
                bill_lines.append((0, 0, {
                    'product_id': pol.product_id.id,
                    'name': pol.name or pol.product_id.display_name,
                    'quantity': pol.product_qty,
                    'product_uom_id': pol.product_uom_id.id,
                    'price_unit': pol.price_unit,
                    'account_id': account.id,
                }))
            if bill_lines:
                bill_vals = {
                    'move_type': 'in_invoice',
                    'partner_id': supplying_company.intercompany_partner_id.id,
                    'company_id': buying_company.id,
                    'invoice_origin': po.name,
                    'invoice_date': fields.Date.today(),
                    'invoice_line_ids': bill_lines,
                }
                if purchase_journal:
                    bill_vals['journal_id'] = purchase_journal.id
                vendor_bill = AccountMove.with_company(buying_company).create(bill_vals)
                if purchase_journal:
                    vendor_bill.with_company(buying_company).action_post()
                    _logger.warning('ICF: Posted vendor bill %s in %s',
                                 vendor_bill.name, buying_company.name)
                else:
                    _logger.warning('ICF: Vendor bill %s created as draft in %s — no purchase journal found, please post manually',
                                    vendor_bill.name, buying_company.name)
                if log:
                    log.vendor_bill_id = vendor_bill.id
            else:
                _logger.warning('ICF: No bill lines for PO %s — bill skipped', po.name)
        except Exception as exc:
            _logger.warning('ICF: Could not create vendor bill for PO %s: %s', po.name, exc)

        # ── Customer Invoice in supplying company ─────────────────────────
        try:
            sale_journal = _get_journal(supplying_company, 'sale')
            inv_lines = []
            for sol in ic_so.order_line:
                account = _get_account(sol.product_id, supplying_company, 'income')
                if not account:
                    _logger.warning('ICF: No income account for %s in %s',
                                    sol.product_id.display_name, supplying_company.name)
                    continue
                inv_lines.append((0, 0, {
                    'product_id': sol.product_id.id,
                    'name': sol.name or sol.product_id.display_name,
                    'quantity': sol.product_uom_qty,
                    'product_uom_id': sol.product_uom_id.id,
                    'price_unit': sol.price_unit,
                    'account_id': account.id,
                }))
            if inv_lines:
                inv_vals = {
                    'move_type': 'out_invoice',
                    'partner_id': buying_company.intercompany_partner_id.id,
                    'company_id': supplying_company.id,
                    'invoice_origin': ic_so.name,
                    'invoice_date': fields.Date.today(),
                    'invoice_line_ids': inv_lines,
                }
                if sale_journal:
                    inv_vals['journal_id'] = sale_journal.id
                customer_invoice = AccountMove.with_company(supplying_company).create(inv_vals)
                if sale_journal:
                    customer_invoice.with_company(supplying_company).action_post()
                    _logger.warning('ICF: Posted customer invoice %s in %s',
                                    customer_invoice.name, supplying_company.name)
                else:
                    _logger.warning('ICF: Customer invoice %s created as draft in %s — no sale journal',
                                    customer_invoice.name, supplying_company.name)
                if log:
                    log.customer_invoice_id = customer_invoice.id
            else:
                _logger.warning('ICF: No invoice lines for SO %s — invoice skipped', ic_so.name)
        except Exception as exc:
            _logger.warning('ICF: Could not create customer invoice for SO %s: %s', ic_so.name, exc)

    def _create_intercompany_po(self, line, qty, buying_company, supplying_company):
        """Create a Purchase Order in *buying_company* at cost price."""
        # Use the product's cost price in the supplying company's context
        # so both sides of the intercompany transaction use the same value
        price_unit = line.product_id.with_company(supplying_company).standard_price

        return self.env['purchase.order'].sudo().with_company(buying_company).create({
            'partner_id': supplying_company.intercompany_partner_id.id,
            'company_id': buying_company.id,
            'origin': self.name,
            'order_line': [(0, 0, {
                'product_id': line.product_id.id,
                'product_qty': qty,
                'product_uom_id': line.product_uom_id.id,
                'price_unit': price_unit,
                'name': line.product_id.display_name,
                'date_planned': fields.Datetime.now(),
            })],
        })

    def _create_intercompany_so(self, line, qty, buying_company, supplying_company,
                                 purchase_order):
        """Create a Sales Order in *supplying_company*.

        is_intercompany_so=True is stamped on this record so that when
        action_confirm is called on it, _trigger_intercompany_flow is
        intentionally skipped — the supplying company is fulfilling from
        its own confirmed stock, not re-sourcing further up the chain.
        """
        # Always use cost price for intercompany — not the sales list price
        price_unit = line.product_id.with_company(supplying_company).standard_price

        return self.env['sale.order'].sudo().with_company(supplying_company).create({
            'partner_id': buying_company.intercompany_partner_id.id,
            'company_id': supplying_company.id,
            'origin': purchase_order.name,
            'client_order_ref': purchase_order.name,
            'is_intercompany_so': True,          # ← loop guard
            'order_line': [(0, 0, {
                'product_id': line.product_id.id,
                'product_uom_qty': qty,
                'product_uom_id': line.product_uom_id.id,
                'price_unit': price_unit,
                'name': line.product_id.display_name,
            })],
        })

    # ─────────────────────────────────────────────────────────────────────────
    # Smart button
    # ─────────────────────────────────────────────────────────────────────────

    def action_view_intercompany_flows(self):
        self.ensure_one()
        return {
            'name': _('Intercompany Flows'),
            'type': 'ir.actions.act_window',
            'res_model': 'intercompany.flow.log',
            'view_mode': 'list,form',
            'domain': [('origin_sale_id', '=', self.id)],
            'context': {'default_origin_sale_id': self.id},
        }
