# -*- coding: utf-8 -*-
import logging
from odoo import models, fields, api, _
from odoo.exceptions import UserError

_logger = logging.getLogger(__name__)


class SaleOrder(models.Model):
    _inherit = 'sale.order'

    intercompany_flow_log_ids = fields.One2many(
        'intercompany.flow.log', 'origin_sale_id',
        string='Intercompany Flow Logs',
    )
    intercompany_flow_count = fields.Integer(
        compute='_compute_intercompany_flow_count',
        string='Intercompany Flows',
    )
    is_intercompany_so = fields.Boolean(
        string='Intercompany Auto Flow SO',
        default=False,
        copy=False,
        help='Set to True on SOs that were auto-generated by the intercompany '
             'flow engine. Prevents the trigger from re-firing on these orders '
             'and causing circular sourcing chains.',
    )

    @api.depends('intercompany_flow_log_ids')
    def _compute_intercompany_flow_count(self):
        for order in self:
            order.intercompany_flow_count = len(order.intercompany_flow_log_ids)

    def action_confirm(self):
        res = super().action_confirm()
        for order in self:
            _logger.info(
                'ICF CHECK: SO %s | company=%s | auto_flow=%s | is_ic_so=%s',
                order.name,
                order.company_id.name,
                order.company_id.intercompany_auto_flow,
                order.is_intercompany_so,
            )
            if order.company_id.intercompany_auto_flow and not order.is_intercompany_so:
                order._trigger_intercompany_flow()
        return res

    # ─────────────────────────────────────────────────────────────────────────
    # Core orchestration
    # ─────────────────────────────────────────────────────────────────────────

    def _trigger_intercompany_flow(self):
        """For each SO line with a storable product, check local stock and
        automatically source any shortage from one or more sibling companies.

        Algorithm:
          1. Compute shortage = ordered qty - local unreserved stock.
          2. Build a ranked list of ALL sibling companies with available stock
             (ranked: highest qty first, minimises number of POs raised).
          3. If one company can cover the full shortage -> single PO/SO pair.
          4. If no single company can -> split across multiple companies,
             each getting a separate PO/SO pair for its portion.
          5. If total available across all siblings < shortage -> create POs
             for what's available, warn on chatter about unfulfilled remainder.
        """
        self.ensure_one()
        selling_company = self.company_id
        _logger.info('ICF: _trigger_intercompany_flow called for SO %s (%s lines)', self.name, len(self.order_line))

        for line in self.order_line.filtered(
            lambda l: l.product_id and l.product_id.type != 'service'
                      and (
                          getattr(l.product_id, 'is_storable', False)
                          or l.product_id.type == 'product'
                      )
        ):
            _logger.info(
                'ICF: Processing line — product=%s type=%s is_storable=%s',
                line.product_id.display_name,
                line.product_id.type,
                getattr(line.product_id, 'is_storable', 'N/A'),
            )
            needed_qty = line.product_uom_qty
            local_qty  = self._get_local_available_qty(line.product_id, selling_company)
            shortage   = needed_qty - local_qty

            if shortage <= 0:
                continue  # Enough local stock — nothing to do

            _logger.info(
                'ICF: %s needs %.2f of %s; local %.2f -> shortage %.2f',
                selling_company.name, needed_qty,
                line.product_id.display_name, local_qty, shortage,
            )

            # ── Rank ALL sibling companies by available qty (desc) ────────
            ranked = self._rank_supplier_companies(line.product_id, selling_company)
            # ranked = [(company, avail_qty), ...] highest stock first

            if not ranked:
                self._warn_no_stock(line, shortage)
                continue

            # ── Single-source: best company alone covers the shortage ──────
            best_company, best_qty = ranked[0]
            if best_qty >= shortage:
                _logger.info(
                    'ICF: Single-source -> %s has %.2f (need %.2f)',
                    best_company.name, best_qty, shortage,
                )
                self._create_intercompany_pair(
                    line=line,
                    qty=shortage,
                    buying_company=selling_company,
                    supplying_company=best_company,
                )
                continue

            # ── Split-source: spread across multiple companies ────────────
            total_available = sum(qty for _, qty in ranked)
            _logger.info(
                'ICF: Split-source needed — total available %.2f across %d '
                'companies for shortage %.2f',
                total_available, len(ranked), shortage,
            )

            remaining = shortage
            for supplier_company, avail_qty in ranked:
                if remaining <= 0:
                    break
                portion = min(avail_qty, remaining)
                _logger.info(
                    'ICF: Sourcing %.2f from %s (avail %.2f)',
                    portion, supplier_company.name, avail_qty,
                )
                self._create_intercompany_pair(
                    line=line,
                    qty=portion,
                    buying_company=selling_company,
                    supplying_company=supplier_company,
                )
                remaining -= portion

            if remaining > 0:
                self._warn_partial_stock(
                    line, shortage,
                    sourced=shortage - remaining,
                    unfulfilled=remaining,
                )

    # ─────────────────────────────────────────────────────────────────────────
    # Stock helpers
    # ─────────────────────────────────────────────────────────────────────────

    def _get_local_available_qty(self, product, company):
        """Return unreserved on-hand qty of *product* across all internal
        locations owned by *company*."""
        internal_locations = self.env['stock.location'].sudo().search([
            ('company_id', '=', company.id),
            ('usage', '=', 'internal'),
        ])
        if not internal_locations:
            return 0.0
        quants = self.env['stock.quant'].sudo().search([
            ('product_id', '=', product.id),
            ('location_id', 'in', internal_locations.ids),
        ])
        return max(
            0.0,
            sum(quants.mapped('quantity')) - sum(quants.mapped('reserved_quantity'))
        )

    def _rank_supplier_companies(self, product, buying_company):
        """Scan ALL candidate sibling companies and return a ranked list of
        (company, available_qty) sorted by available qty descending.

        Ranking highest-first means:
          - We always prefer a single supplier over a split when possible.
          - When splitting is unavoidable, we exhaust the largest source
            first, minimising the total number of PO/SO pairs created.
        """
        candidates = buying_company._get_intercompany_supplier_candidates()
        ranked = []
        for company in candidates:
            avail = self._get_local_available_qty(product, company)
            _logger.info(
                'ICF: Scanning %s -> %.2f available of %s',
                company.name, avail, product.display_name,
            )
            if avail > 0:
                ranked.append((company, avail))

        ranked.sort(key=lambda x: x[1], reverse=True)
        return ranked

    # ─────────────────────────────────────────────────────────────────────────
    # Chatter warnings
    # ─────────────────────────────────────────────────────────────────────────

    def _warn_no_stock(self, line, shortage):
        self.message_post(
            body=_(
                'Intercompany Auto Flow: No sibling company has any stock of '
                '<b>%(product)s</b> (shortage: %(qty).2f %(uom)s). '
                'Please source manually.',
                product=line.product_id.display_name,
                qty=shortage,
                uom=line.product_uom_id.name,
            )
        )

    def _warn_partial_stock(self, line, shortage, sourced, unfulfilled):
        self.message_post(
            body=_(
                'Intercompany Auto Flow: <b>%(product)s</b> — shortage was '
                '%(shortage).2f %(uom)s. Sourced %(sourced).2f %(uom)s from '
                'sibling companies across multiple POs. '
                '<b>%(unfulfilled).2f %(uom)s still unfulfilled</b> — '
                'please source the remainder manually.',
                product=line.product_id.display_name,
                uom=line.product_uom_id.name,
                shortage=shortage,
                sourced=sourced,
                unfulfilled=unfulfilled,
            )
        )

    # ─────────────────────────────────────────────────────────────────────────
    # Document creation
    # ─────────────────────────────────────────────────────────────────────────

    def _create_intercompany_pair(self, line, qty, buying_company, supplying_company):
        """Create a PO in *buying_company* and a matching SO in
        *supplying_company*, confirm both, and write a flow log entry."""
        log = self.env['intercompany.flow.log'].sudo().create({
            'name': self.env['ir.sequence'].next_by_code('intercompany.flow.log') or 'ICF-NEW',
            'origin_sale_id': self.id,
            'buying_company_id': buying_company.id,
            'supplying_company_id': supplying_company.id,
            'product_id': line.product_id.id,
            'product_qty': qty,
            'product_uom_id': line.product_uom_id.id,
            'state': 'draft',
        })

        try:
            # Step 1: Purchase Order in buying company
            po = self._create_intercompany_po(
                line=line, qty=qty,
                buying_company=buying_company,
                supplying_company=supplying_company,
            )
            log.purchase_order_id = po.id

            # Step 2: Sales Order in supplying company
            ic_so = self._create_intercompany_so(
                line=line, qty=qty,
                buying_company=buying_company,
                supplying_company=supplying_company,
                purchase_order=po,
            )
            log.intercompany_sale_id = ic_so.id

            # Step 3: Auto-confirm
            if supplying_company.intercompany_sale_auto_confirm:
                ic_so.with_company(supplying_company).action_confirm()

            if buying_company.intercompany_purchase_auto_confirm:
                po.with_company(buying_company).button_confirm()

            # Step 4: Record picking counts for traceability
            log.stock_picking_out_count = len(ic_so.picking_ids)
            log.stock_picking_in_count = len(po.picking_ids)

            # Step 5: Auto-validate pickings if configured
            if buying_company.intercompany_auto_validate_pickings:
                self._auto_validate_pickings(
                    out_pickings=ic_so.picking_ids,
                    in_pickings=po.picking_ids,
                    supplying_company=supplying_company,
                    buying_company=buying_company,
                )

            log.state = 'done'

            # Step 5: Chatter
            self.message_post(
                body=_(
                    'Intercompany Auto Flow: '
                    '<a href="/odoo/purchase/%(po_id)s">%(po_name)s</a> '
                    '(PO in %(buyer)s) &#8596; '
                    '<a href="/odoo/sales/%(so_id)s">%(so_name)s</a> '
                    '(SO in %(supplier)s) &mdash; '
                    '<b>%(product)s &times; %(qty).2f %(uom)s</b>.',
                    po_id=po.id, po_name=po.name,
                    buyer=buying_company.name,
                    so_id=ic_so.id, so_name=ic_so.name,
                    supplier=supplying_company.name,
                    product=line.product_id.display_name,
                    qty=qty, uom=line.product_uom_id.name,
                )
            )
            _logger.info('ICF: Complete — PO %s <-> SO %s', po.name, ic_so.name)

        except Exception as exc:
            log.state = 'error'
            log.error_message = str(exc)
            _logger.exception('ICF: Flow failed — %s', exc)
            self.message_post(
                body=_(
                    'Intercompany Auto Flow ERROR for <b>%(product)s</b> '
                    '(%(buyer)s <- %(supplier)s): %(err)s',
                    product=line.product_id.display_name,
                    buyer=buying_company.name,
                    supplier=supplying_company.name,
                    err=exc,
                )
            )

    def _auto_validate_pickings(self, out_pickings, in_pickings, supplying_company, buying_company):
        """Immediately validate all pickings for both companies.

        Called when intercompany_auto_validate_pickings is True — typically
        when companies share a physical warehouse and the stock transfer is
        a purely legal/accounting movement between entities.

        Sequence:
          1. Validate outgoing pickings in the supplying company first
             (goods leave B's books).
          2. Validate incoming pickings in the buying company next
             (goods arrive on A's books).

        For each picking we call _action_done() directly rather than
        button_validate() to avoid wizard pop-ups (backorder, immediate
        transfer) that would block the automated flow. We set all move
        demand quantities as done before calling _action_done().
        """
        Picking = self.env['stock.picking'].sudo()

        # ── Outgoing (supplying company) ──────────────────────────────────
        for picking in out_pickings.with_company(supplying_company):
            if picking.state in ('done', 'cancel'):
                continue
            try:
                # Ensure all move lines have qty_done set
                for move in picking.move_ids.filtered(lambda m: m.state not in ('done', 'cancel')):
                    move.quantity = move.product_uom_qty
                picking.with_context(skip_backorder=True, skip_immediate=True)._action_done()
                _logger.info('ICF: Auto-validated outgoing picking %s', picking.name)
            except Exception as exc:
                _logger.warning('ICF: Could not auto-validate outgoing picking %s: %s', picking.name, exc)

        # ── Incoming (buying company) ─────────────────────────────────────
        for picking in in_pickings.with_company(buying_company):
            if picking.state in ('done', 'cancel'):
                continue
            try:
                for move in picking.move_ids.filtered(lambda m: m.state not in ('done', 'cancel')):
                    move.quantity = move.product_uom_qty
                picking.with_context(skip_backorder=True, skip_immediate=True)._action_done()
                _logger.info('ICF: Auto-validated incoming picking %s', picking.name)
            except Exception as exc:
                _logger.warning('ICF: Could not auto-validate incoming picking %s: %s', picking.name, exc)

    def _create_intercompany_po(self, line, qty, buying_company, supplying_company):
        """Create a Purchase Order in *buying_company*."""
        supplier_info = line.product_id.seller_ids.filtered(
            lambda s: s.partner_id == supplying_company.intercompany_partner_id
        )[:1]
        price_unit = supplier_info.price if supplier_info else line.product_id.standard_price

        return self.env['purchase.order'].sudo().with_company(buying_company).create({
            'partner_id': supplying_company.intercompany_partner_id.id,
            'company_id': buying_company.id,
            'origin': self.name,
            'order_line': [(0, 0, {
                'product_id': line.product_id.id,
                'product_qty': qty,
                'product_uom_id': line.product_uom_id.id,
                'price_unit': price_unit,
                'name': line.product_id.display_name,
                'date_planned': fields.Datetime.now(),
            })],
        })

    def _create_intercompany_so(self, line, qty, buying_company, supplying_company,
                                 purchase_order):
        """Create a Sales Order in *supplying_company*.

        is_intercompany_so=True is stamped on this record so that when
        action_confirm is called on it, _trigger_intercompany_flow is
        intentionally skipped — the supplying company is fulfilling from
        its own confirmed stock, not re-sourcing further up the chain.
        """
        price_unit = line.product_id.with_company(supplying_company).lst_price

        return self.env['sale.order'].sudo().with_company(supplying_company).create({
            'partner_id': buying_company.intercompany_partner_id.id,
            'company_id': supplying_company.id,
            'origin': purchase_order.name,
            'client_order_ref': purchase_order.name,
            'is_intercompany_so': True,          # ← loop guard
            'order_line': [(0, 0, {
                'product_id': line.product_id.id,
                'product_uom_qty': qty,
                'product_uom_id': line.product_uom_id.id,
                'price_unit': price_unit,
                'name': line.product_id.display_name,
            })],
        })

    # ─────────────────────────────────────────────────────────────────────────
    # Smart button
    # ─────────────────────────────────────────────────────────────────────────

    def action_view_intercompany_flows(self):
        self.ensure_one()
        return {
            'name': _('Intercompany Flows'),
            'type': 'ir.actions.act_window',
            'res_model': 'intercompany.flow.log',
            'view_mode': 'list,form',
            'domain': [('origin_sale_id', '=', self.id)],
            'context': {'default_origin_sale_id': self.id},
        }
